
image: composer:2.0


pipelines:
  default:
    - parallel:
      - step:
        name: Build
        script:
          - composer install
        caches:
          - composer
        artifacts:
          - vendor/**
        # - step:
        #     name: Test
        #     script:
        #       - composer install
        #       -  ./vendor/bin/phpunit test
        #     caches:
        #       - composer
        # - step:
        #     name: Lint
        #     script:
        #       - composer install
        #       - ./vendor/bin/phplint . --exclude=vendor
        #     caches:
        #       - composer
